version: '3'

services:

  proxy:
    container_name: quibana-proxy
    build: proxy
    links:
      - client:client
      - server:server
      - mongodb:mongodb
    ports:
      - "80:80"
    networks:
      - quibana-network
    depends_on:
      - server
      - client
      - mongodb

  server:
    container_name: quibana-server
    build: server
    ports:
      - "3000:3000"
    environment:
      - API_HOST=localhost
      - API_PORT=3000
    networks:
      - quibana-network
    depends_on:
      - mongodb

  client:
    container_name: quibana-client
    build: client
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - quibana-network
    depends_on:
      - server

  mongodb:
    container_name: quibana-database
    image: mongo:3.2.6
    ports:
      - 27018:27017
    networks:
      - quibana-network

  # import-database:
  #   container_name: quibana-database-importer
  #   image: mongo:3.2.6
  #   links:
  #     - mongodb
  #   volumes:
  #     - ./mongodb:/mongodb
  #   command:
  #     /mongodb/import.sh
