### Variables
@user = { "email": "hello@email.com", "password": "password"}

### Register user given their email and password, returns the token upon successful registration
POST  http://localhost:3000/api/user
content-type: application/json

{{user}}